import {
  Globe, Smartphone, Palette, Code2, Building2, Cloud, Brain, GitMerge, Shield, Wrench, Zap
} from 'lucide-react'

export const services = [
  {
    id: 'web-development',
    icon: Globe,
    title: 'Web Development',
    shortDesc: 'High-performance websites and web applications engineered for scale, speed, and conversion.',
    to: '/services/web-development',
    color: '#2563eb',
    overview: 'We build robust, scalable web solutions that combine cutting-edge technology with intuitive user experiences. From corporate portals to complex web applications, every line of code we write serves a strategic business purpose.',
    features: [
      'Custom frontend development with React, Vue, or Angular',
      'Scalable backend architecture with Node.js, Laravel, or Python',
      'Progressive Web Apps (PWAs) for offline-first experiences',
      'Headless CMS integration (Contentful, Strapi, Sanity)',
      'E-commerce platform development and optimization',
      'API-first development with RESTful and GraphQL interfaces',
    ],
    benefits: [
      { title: 'Faster Time-to-Market', desc: 'Agile development cycles deliver your product weeks ahead of traditional timelines.' },
      { title: 'SEO-Ready Architecture', desc: 'Built with search engine optimization baked in from day one, not as an afterthought.' },
      { title: 'Performance-First Approach', desc: 'Optimized for Core Web Vitals, targeting sub-2-second load times.' },
      { title: 'Future-Proof Technology', desc: 'Modern stacks ensure your investment remains viable for years ahead.' },
    ],
    process: [
      { step: '01', title: 'Discovery & Strategy', desc: 'Deep-dive into your business goals, audience, and technical requirements.' },
      { step: '02', title: 'Architecture Planning', desc: 'Design system architecture, database schema, and integration blueprints.' },
      { step: '03', title: 'Design & Prototype', desc: 'Craft pixel-perfect UI designs and interactive prototypes for validation.' },
      { step: '04', title: 'Development & Testing', desc: 'Agile sprints with continuous testing and stakeholder reviews.' },
      { step: '05', title: 'Launch & Optimize', desc: 'Smooth deployment, performance monitoring, and iterative improvements.' },
    ],
    technologies: ['React.js', 'Next.js', 'Vue.js', 'Node.js', 'Laravel', 'PostgreSQL', 'Redis', 'Docker'],
    industries: ['E-commerce', 'Healthcare', 'Finance', 'Education', 'Real Estate', 'SaaS'],
    faqs: [
      { question: 'How long does a typical web development project take?', answer: 'Project timelines vary by complexity. A standard corporate website typically takes 6–10 weeks, while complex web applications may require 3–6 months. We provide precise timelines after our discovery phase.' },
      { question: 'Do you provide post-launch support?', answer: 'Yes. All our projects include a 30-day post-launch support period. We also offer ongoing maintenance packages tailored to your needs.' },
      { question: 'Can you redesign our existing website?', answer: 'Absolutely. We specialize in website redesigns that improve performance, visual appeal, and conversion rates while preserving your SEO equity.' },
    ],
  },
  {
    id: 'mobile-app-development',
    icon: Smartphone,
    title: 'Mobile App Development',
    shortDesc: 'Native and cross-platform mobile applications that users love and businesses rely on.',
    to: '/services/mobile-app-development',
    color: '#7c3aed',
    overview: 'From concept to App Store, we design and develop mobile applications that deliver exceptional user experiences across iOS and Android platforms. Our mobile solutions are performance-optimized, scalable, and built for real-world usage patterns.',
    features: [
      'Native iOS development with Swift and SwiftUI',
      'Native Android development with Kotlin and Jetpack Compose',
      'Cross-platform apps with React Native and Flutter',
      'Offline-first architecture with local data synchronization',
      'Push notifications, deep linking, and in-app purchases',
      'Integration with device hardware (camera, GPS, biometrics)',
    ],
    benefits: [
      { title: 'Cross-Platform Efficiency', desc: 'One codebase, two platforms — reducing development cost by up to 40%.' },
      { title: 'Native Performance', desc: 'Apps that feel genuinely native, with fluid 60fps animations and instant responses.' },
      { title: 'App Store Optimized', desc: 'Built following platform guidelines to ensure smooth review and approval.' },
      { title: 'Scalable Architecture', desc: 'Designed to grow from 1,000 to 10 million users without re-architecture.' },
    ],
    process: [
      { step: '01', title: 'Requirements Analysis', desc: 'Map out features, user flows, and technical constraints.' },
      { step: '02', title: 'UX/UI Design', desc: 'Design intuitive interfaces following platform-specific design guidelines.' },
      { step: '03', title: 'Development Sprints', desc: 'Iterative development with bi-weekly demos and feedback loops.' },
      { step: '04', title: 'QA & Performance Testing', desc: 'Rigorous testing across devices, OS versions, and network conditions.' },
      { step: '05', title: 'App Store Submission', desc: 'Handle all submission requirements and post-launch monitoring.' },
    ],
    technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase', 'AWS Amplify', 'Stripe SDK', 'Expo'],
    industries: ['Retail', 'Healthcare', 'Food & Beverage', 'Finance', 'Education', 'Logistics'],
    faqs: [
      { question: 'Should I choose native or cross-platform development?', answer: 'For most businesses, cross-platform (React Native or Flutter) offers the best balance of quality and cost. Native development is recommended for apps requiring deep hardware integration or maximum performance, such as AR/VR or real-time video.' },
      { question: 'How do you handle App Store rejections?', answer: 'We follow platform guidelines strictly and include pre-submission reviews to minimize rejection risk. If a rejection occurs, we handle revisions and resubmission at no additional cost.' },
    ],
  },
  {
    id: 'ui-ux-design',
    icon: Palette,
    title: 'UI/UX Design',
    shortDesc: 'Research-driven design systems that transform user behavior into intuitive, beautiful interfaces.',
    to: '/services/ui-ux-design',
    color: '#06b6d4',
    overview: 'Great design is the difference between a product that users abandon and one they champion. Our UX team combines behavioral research, strategic thinking, and visual craft to create digital experiences that convert visitors into loyal customers.',
    features: [
      'User research, personas, and journey mapping',
      'Information architecture and content strategy',
      'Wireframing and interactive prototyping',
      'Design system creation and documentation',
      'Usability testing and A/B experimentation',
      'Motion design and micro-interaction specifications',
    ],
    benefits: [
      { title: 'Higher Conversion Rates', desc: 'Data-driven UX decisions typically increase conversions by 25–40%.' },
      { title: 'Reduced Development Cost', desc: 'Detailed design specs eliminate ambiguity and costly rework during development.' },
      { title: 'Brand Consistency', desc: 'A unified design system ensures visual coherence across all touchpoints.' },
      { title: 'Accessible by Default', desc: 'WCAG 2.1 AA compliance built into every design decision.' },
    ],
    process: [
      { step: '01', title: 'Research & Discovery', desc: 'User interviews, competitive analysis, and heuristic evaluation.' },
      { step: '02', title: 'Strategy & Architecture', desc: 'Define information hierarchy, navigation patterns, and content structure.' },
      { step: '03', title: 'Wireframes & Flow', desc: 'Low-fidelity wireframes validated with stakeholders before visual design.' },
      { step: '04', title: 'Visual Design', desc: 'High-fidelity UI designs with a comprehensive design system.' },
      { step: '05', title: 'Prototype & Test', desc: 'Interactive prototypes tested with real users for validation.' },
    ],
    technologies: ['Figma', 'Adobe XD', 'Maze', 'Hotjar', 'Storybook', 'Lottie', 'Framer', 'Zeplin'],
    industries: ['SaaS', 'E-commerce', 'Healthcare', 'Finance', 'Education', 'Entertainment'],
    faqs: [
      { question: 'What deliverables will I receive?', answer: 'You receive complete Figma design files, a design system (component library, typography, colors, spacing), interactive prototypes, and developer handoff documentation with precise specifications.' },
    ],
  },
  {
    id: 'software-development',
    icon: Code2,
    title: 'Software Development',
    shortDesc: 'Custom enterprise software that automates workflows, reduces costs, and scales with your business.',
    to: '/services/software-development',
    color: '#10b981',
    overview: 'We architect and build custom software solutions that address your unique business challenges. From internal tools to complex enterprise platforms, our software engineering team delivers robust, maintainable, and scalable applications.',
    features: [
      'Custom ERP and CRM development',
      'Workflow automation and BPM systems',
      'Legacy system modernization and migration',
      'API development and third-party integrations',
      'Real-time data processing and reporting dashboards',
      'Multi-tenant SaaS platform architecture',
    ],
    benefits: [
      { title: 'Tailored to Your Workflows', desc: 'Software built precisely around your processes, not generic one-size-fits-all solutions.' },
      { title: 'Competitive Advantage', desc: 'Proprietary software becomes a defensible business asset your competitors cannot replicate.' },
      { title: 'Reduced Operational Costs', desc: 'Automation of manual processes typically reduces operational overhead by 30–60%.' },
      { title: 'Full Ownership', desc: 'You own 100% of the source code with no vendor lock-in.' },
    ],
    process: [
      { step: '01', title: 'Business Analysis', desc: 'Document current workflows, pain points, and desired outcomes.' },
      { step: '02', title: 'Technical Specification', desc: 'Define system architecture, data models, and integration requirements.' },
      { step: '03', title: 'Iterative Development', desc: 'Build in functional sprints with continuous stakeholder reviews.' },
      { step: '04', title: 'Integration & Testing', desc: 'System integration, user acceptance testing, and performance validation.' },
      { step: '05', title: 'Deployment & Training', desc: 'Production deployment with comprehensive user training and documentation.' },
    ],
    technologies: ['Python', 'Java', 'Node.js', 'PostgreSQL', 'MongoDB', 'Redis', 'RabbitMQ', 'Elasticsearch'],
    industries: ['Manufacturing', 'Healthcare', 'Finance', 'Logistics', 'Retail', 'Government'],
    faqs: [
      { question: 'How do you ensure data security in custom software?', answer: 'We implement multiple security layers: encrypted data storage, role-based access control, audit logging, regular security audits, and compliance with relevant standards (GDPR, HIPAA as applicable).' },
    ],
  },
  {
    id: 'enterprise-solutions',
    icon: Building2,
    title: 'Enterprise Solutions',
    shortDesc: 'Scalable enterprise platforms that integrate your entire technology ecosystem.',
    to: '/services/enterprise-solutions',
    color: '#f59e0b',
    overview: 'Enterprise organizations require technology that matches their scale and complexity. We deliver integrated solutions that unify disparate systems, improve data visibility, and enable intelligent decision-making across the entire organization.',
    features: [
      'Enterprise Resource Planning (ERP) implementation and customization',
      'Customer Relationship Management (CRM) development',
      'Business Intelligence and analytics dashboards',
      'Supply chain and inventory management systems',
      'HR and payroll management platforms',
      'Document management and workflow automation',
    ],
    benefits: [
      { title: 'Unified Data Visibility', desc: 'Break down departmental silos with integrated data flowing across systems.' },
      { title: 'Operational Efficiency', desc: 'Eliminate duplicate data entry and streamline cross-departmental workflows.' },
      { title: 'Real-Time Reporting', desc: 'Executive dashboards providing instant visibility into business performance.' },
      { title: 'Compliance Ready', desc: 'Built-in audit trails and reporting for regulatory compliance.' },
    ],
    process: [
      { step: '01', title: 'Enterprise Assessment', desc: 'Audit current systems, processes, and integration requirements.' },
      { step: '02', title: 'Solution Architecture', desc: 'Design integration architecture and data flow between systems.' },
      { step: '03', title: 'Phased Implementation', desc: 'Incremental rollout to minimize business disruption.' },
      { step: '04', title: 'Data Migration', desc: 'Safe, validated migration of existing data to new systems.' },
      { step: '05', title: 'Training & Adoption', desc: 'Comprehensive training programs to drive user adoption.' },
    ],
    technologies: ['SAP Integration', 'Salesforce', 'Microsoft Dynamics', 'Oracle', 'Power BI', 'Tableau', 'MuleSoft'],
    industries: ['Manufacturing', 'Retail', 'Healthcare', 'Finance', 'Real Estate', 'Education'],
    faqs: [],
  },
  {
    id: 'cloud-solutions',
    icon: Cloud,
    title: 'Cloud Solutions',
    shortDesc: 'Cloud strategy, migration, and managed services that reduce infrastructure costs and boost reliability.',
    to: '/services/cloud-solutions',
    color: '#06b6d4',
    overview: 'Harness the full potential of cloud computing with our end-to-end cloud services. We help businesses migrate to the cloud, optimize cloud spend, and build cloud-native applications that are resilient, scalable, and cost-efficient.',
    features: [
      'Cloud strategy and readiness assessment',
      'Lift-and-shift and re-architected cloud migrations',
      'Serverless architecture design and implementation',
      'Container orchestration with Kubernetes and Docker',
      'Cloud cost optimization and FinOps practices',
      'Multi-cloud and hybrid cloud strategies',
    ],
    benefits: [
      { title: 'Significant Cost Reduction', desc: 'Move from CapEx to OpEx and reduce infrastructure costs by 30–50%.' },
      { title: '99.99% Uptime SLA', desc: 'Leverage cloud providers\' global infrastructure for maximum availability.' },
      { title: 'Elastic Scalability', desc: 'Scale resources up or down in seconds to match demand.' },
      { title: 'Enhanced Security', desc: 'Cloud-native security tools and best practices baked into architecture.' },
    ],
    process: [
      { step: '01', title: 'Cloud Assessment', desc: 'Evaluate current infrastructure and define cloud migration strategy.' },
      { step: '02', title: 'Architecture Design', desc: 'Design target cloud architecture optimized for performance and cost.' },
      { step: '03', title: 'Migration Execution', desc: 'Execute migration in phases with zero-downtime strategies.' },
      { step: '04', title: 'Optimization', desc: 'Right-size resources and implement cost governance policies.' },
      { step: '05', title: 'Managed Operations', desc: 'Ongoing monitoring, security patching, and performance optimization.' },
    ],
    technologies: ['AWS', 'Microsoft Azure', 'Google Cloud', 'Kubernetes', 'Terraform', 'Ansible', 'Prometheus', 'Grafana'],
    industries: ['SaaS', 'E-commerce', 'Healthcare', 'Finance', 'Media', 'Education'],
    faqs: [],
  },
  {
    id: 'ai-development',
    icon: Brain,
    title: 'AI Development',
    shortDesc: 'Intelligent AI solutions that automate decisions, surface insights, and create competitive advantages.',
    to: '/services/ai-development',
    color: '#7c3aed',
    overview: 'Artificial intelligence is no longer a future concept — it\'s a present competitive necessity. We build practical AI solutions that solve real business problems: from intelligent automation and predictive analytics to natural language processing and computer vision.',
    features: [
      'Custom machine learning model development and training',
      'Generative AI integration (GPT, Claude, Gemini APIs)',
      'Natural Language Processing (NLP) for text analysis',
      'Computer vision for image and video analysis',
      'Predictive analytics and demand forecasting',
      'AI-powered chatbots and virtual assistants',
    ],
    benefits: [
      { title: 'Intelligent Automation', desc: 'Automate complex decision-making processes that previously required human expertise.' },
      { title: 'Predictive Capabilities', desc: 'Anticipate customer behavior, demand trends, and operational issues before they occur.' },
      { title: 'Competitive Differentiation', desc: 'AI capabilities that competitors take years to replicate.' },
      { title: 'Continuous Improvement', desc: 'Models that learn and improve from new data over time.' },
    ],
    process: [
      { step: '01', title: 'Problem Definition', desc: 'Identify and validate the AI use case with measurable success metrics.' },
      { step: '02', title: 'Data Assessment', desc: 'Evaluate data availability, quality, and augmentation requirements.' },
      { step: '03', title: 'Model Development', desc: 'Train, evaluate, and iterate on models using appropriate algorithms.' },
      { step: '04', title: 'Integration', desc: 'Embed AI capabilities seamlessly into existing systems and workflows.' },
      { step: '05', title: 'Monitoring & Retraining', desc: 'Ongoing model performance monitoring with scheduled retraining.' },
    ],
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI API', 'LangChain', 'Hugging Face', 'FastAPI', 'Pinecone'],
    industries: ['Healthcare', 'Finance', 'Retail', 'Manufacturing', 'Logistics', 'E-commerce'],
    faqs: [],
  },
  {
    id: 'devops',
    icon: GitMerge,
    title: 'DevOps',
    shortDesc: 'Streamlined CI/CD pipelines and infrastructure automation that accelerate delivery and reduce risk.',
    to: '/services/devops',
    color: '#f59e0b',
    overview: 'Bridge the gap between development and operations with our DevOps consulting and implementation services. We help teams ship software faster, more reliably, and with greater confidence through automated pipelines, infrastructure-as-code, and monitoring.',
    features: [
      'CI/CD pipeline design and implementation',
      'Infrastructure as Code (IaC) with Terraform and Ansible',
      'Container orchestration with Docker and Kubernetes',
      'Automated testing and quality gate integration',
      'Security integration (DevSecOps) in the pipeline',
      'Observability setup with logging, metrics, and tracing',
    ],
    benefits: [
      { title: 'Faster Release Cycles', desc: 'Deploy features 10x faster with automated pipelines and reduced manual gates.' },
      { title: 'Higher System Reliability', desc: 'Automated rollbacks and canary deployments reduce production incidents.' },
      { title: 'Reduced Infrastructure Costs', desc: 'IaC eliminates configuration drift and enables efficient resource management.' },
      { title: 'Team Collaboration', desc: 'Break silos between dev, ops, and security teams.' },
    ],
    process: [
      { step: '01', title: 'DevOps Assessment', desc: 'Audit current delivery pipeline, tooling, and team practices.' },
      { step: '02', title: 'Roadmap Design', desc: 'Create a phased DevOps transformation roadmap with quick wins.' },
      { step: '03', title: 'Pipeline Implementation', desc: 'Build and automate CI/CD pipelines with quality gates.' },
      { step: '04', title: 'Infrastructure Automation', desc: 'Implement IaC and container orchestration.' },
      { step: '05', title: 'Enablement', desc: 'Train teams on new workflows and establish DevOps culture.' },
    ],
    technologies: ['Jenkins', 'GitHub Actions', 'GitLab CI', 'Docker', 'Kubernetes', 'Terraform', 'Prometheus', 'ELK Stack'],
    industries: ['SaaS', 'E-commerce', 'Finance', 'Healthcare', 'Media', 'Government'],
    faqs: [],
  },
  {
    id: 'qa-testing',
    icon: Shield,
    title: 'QA & Testing',
    shortDesc: 'Comprehensive quality assurance that ensures your software is bulletproof before it reaches users.',
    to: '/services/qa-testing',
    color: '#10b981',
    overview: 'Quality is not an accident — it is the result of deliberate effort at every stage of development. Our QA team implements systematic testing strategies that identify defects early, reduce rework costs, and build confidence in every release.',
    features: [
      'Test strategy and test plan development',
      'Manual functional and regression testing',
      'Automated testing with Selenium, Playwright, and Cypress',
      'Performance and load testing with JMeter and k6',
      'Security testing and penetration testing',
      'Mobile app testing across devices and OS versions',
    ],
    benefits: [
      { title: 'Early Defect Detection', desc: 'Finding bugs during development is 10x cheaper than fixing them in production.' },
      { title: 'Automated Coverage', desc: 'Regression test suites that run on every code change, providing instant feedback.' },
      { title: 'Performance Assurance', desc: 'Know exactly how your system behaves under peak load before launch.' },
      { title: 'Compliance Validation', desc: 'Ensure regulatory and accessibility compliance with dedicated test suites.' },
    ],
    process: [
      { step: '01', title: 'Test Planning', desc: 'Define scope, test strategy, environments, and success criteria.' },
      { step: '02', title: 'Test Design', desc: 'Create test cases covering functional, edge, and negative scenarios.' },
      { step: '03', title: 'Automation Framework', desc: 'Build scalable automation frameworks integrated into CI/CD.' },
      { step: '04', title: 'Execution & Reporting', desc: 'Execute tests, triage failures, and deliver detailed defect reports.' },
      { step: '05', title: 'Sign-off', desc: 'Formal QA sign-off with release readiness certification.' },
    ],
    technologies: ['Selenium', 'Playwright', 'Cypress', 'JMeter', 'k6', 'Postman', 'JIRA', 'TestRail'],
    industries: ['Finance', 'Healthcare', 'E-commerce', 'SaaS', 'Gaming', 'Government'],
    faqs: [],
  },
  {
    id: 'maintenance',
    icon: Wrench,
    title: 'Maintenance & Support',
    shortDesc: 'Proactive monitoring, updates, and technical support keeping your systems running at peak performance.',
    to: '/services/maintenance',
    color: '#ef4444',
    overview: 'Technology requires continuous care to remain performant, secure, and competitive. Our maintenance and support services provide peace of mind — proactive monitoring catches issues before they impact users, and our team is always available when you need them.',
    features: [
      '24/7 application performance monitoring and alerting',
      'Scheduled security patches and dependency updates',
      'Database performance optimization and backup management',
      'Feature enhancements and bug fix prioritization',
      'Third-party integration maintenance and updates',
      'Monthly performance and security audit reports',
    ],
    benefits: [
      { title: 'Zero Downtime', desc: 'Proactive monitoring and automated failover prevent costly outages.' },
      { title: 'Security Currency', desc: 'Regular patching keeps your applications protected against emerging threats.' },
      { title: 'Dedicated Team', desc: 'A team that knows your systems intimately, providing faster resolution times.' },
      { title: 'Predictable Costs', desc: 'Fixed monthly retainer with no surprise billing for routine maintenance.' },
    ],
    process: [
      { step: '01', title: 'System Audit', desc: 'Comprehensive audit of current system health and technical debt.' },
      { step: '02', title: 'Monitoring Setup', desc: 'Implement monitoring, alerting, and incident management tools.' },
      { step: '03', title: 'Baseline & SLA', desc: 'Establish performance baselines and define SLA commitments.' },
      { step: '04', title: 'Ongoing Operations', desc: 'Regular updates, performance reviews, and proactive optimizations.' },
      { step: '05', title: 'Quarterly Reviews', desc: 'Strategic technology reviews with roadmap recommendations.' },
    ],
    technologies: ['Datadog', 'New Relic', 'PagerDuty', 'Sentry', 'CloudWatch', 'Grafana', 'Git', 'Jira'],
    industries: ['All Industries'],
    faqs: [],
  },
  {
    id: 'digital-transformation',
    icon: Zap,
    title: 'Digital Transformation',
    shortDesc: 'Strategic technology consulting that modernizes your business model and unlocks new revenue streams.',
    to: '/services/digital-transformation',
    color: '#2563eb',
    overview: 'Digital transformation is not simply about adopting new technology — it is about reimagining how your business creates value in the digital age. We partner with leadership teams to define a clear digital strategy and execute it with precision.',
    features: [
      'Digital maturity assessment and transformation roadmap',
      'Legacy system modernization strategy',
      'Customer experience (CX) transformation',
      'Data strategy and analytics capability building',
      'Digital culture and change management advisory',
      'Innovation lab setup and rapid prototyping',
    ],
    benefits: [
      { title: 'Accelerated Innovation', desc: 'Shorten the cycle from idea to market-ready product.' },
      { title: 'New Revenue Streams', desc: 'Digital capabilities that unlock entirely new business model opportunities.' },
      { title: 'Customer-Centric Operations', desc: 'Align your entire organization around delivering superior customer experiences.' },
      { title: 'Data-Driven Decisions', desc: 'Replace intuition-based decisions with real-time data intelligence.' },
    ],
    process: [
      { step: '01', title: 'Diagnostic Assessment', desc: 'Evaluate current digital capabilities, culture, and market position.' },
      { step: '02', title: 'Vision & Strategy', desc: 'Define the target digital state and prioritized transformation roadmap.' },
      { step: '03', title: 'Quick Wins', desc: 'Identify and implement high-impact, low-effort improvements for early momentum.' },
      { step: '04', title: 'Core Transformation', desc: 'Execute foundational technology and process changes.' },
      { step: '05', title: 'Scale & Sustain', desc: 'Embed digital practices into organizational culture for lasting change.' },
    ],
    technologies: ['Cloud Platforms', 'AI & ML', 'IoT', 'Blockchain', 'RPA', 'Data Analytics', 'API Integration'],
    industries: ['Manufacturing', 'Retail', 'Healthcare', 'Finance', 'Government', 'Education'],
    faqs: [],
  },
]

export const servicesForCards = services.map(({ id, icon, title, shortDesc, to }) => ({
  id, icon, title, description: shortDesc, to,
}))
